#!/bin/bash

freq=$1
last=$2

speaker-test -t sine -f $freq -p 1 -l 1 >/dev/null 2>&1 &
pid1=$!
speaker-test -t sine -f $((freq*3)) -p 1 -l 1  >/dev/null 2>&1 &
pid2=$!
speaker-test -t sine -f $((freq*5)) -p 1 -l 1  >/dev/null 2>&1 &
pid3=$!
speaker-test -t sine -f $(bc <<< "scale=5;"$freq" * 3 +8") -p 1 -l 1 >/dev/null 2>&1 &
pid4=$!

sleep $last
kill -9 $pid1 $pid2 $pid3 $pid4 > /dev/null
